version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --user cfn-lint
      - export PATH="$PATH:/root/.local/bin"
      - cfn-lint --version               # shows cfn-lint 1.38.3 in your log
  pre_build:
    commands:
      - echo "PWD=$(pwd)"
      - echo "== repo root =="; ls -la
      - echo "== cfn dir =="; ls -la cfn || true
      - '[ -f cfn/hello-eks.yml ] || { echo "ERROR: cfn/hello-eks.yml not found"; exit 2; }'
  build:
    commands:
      - cfn-lint -t cfn/hello-eks.yml
artifacts:
  files:
    - cfn/hello-eks.yml
