version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint cfn/hello-eks.yaml

artifacts:
  files:
    - cfn/hello-eks.yaml
