version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install cfn-lint
      - python3 -c "import cfnlint, sys; print('cfn-lint installed:', cfnlint.__version__)"
  pre_build:
    commands:
      - echo "PWD=$(pwd)"
      - echo "== repo root =="
      - ls -la
      - echo "== cfn dir =="
      - ls -la cfn || true
      - '[ -f cfn/hello-eks.yml ] || { echo "ERROR: cfn/hello-eks.yml not found"; exit 2; }'
  build:
    commands:
      - python3 -m cfnlint -t cfn/hello-eks.yml
artifacts:
  files:
    - cfn/hello-eks.yml
